name = "notion-sync"
main = "src/index.ts"
compatibility_date = "2023-05-04"

kv_namespaces = [
    { binding = "EVENTS_CACHE", id = "0477eeb9c2994badba9912cbc45da326", preview_id = "7ca10ac99a2b40848cdd55a24dc4f32d" }
]

[triggers]
crons = ["*/1 * * * *"]